### ISSUE TITLE
Cannot connect from remote browser

### ISSUE THREAD

**Issue by ruimgoncalves** [capaj/Moonridge#4]
The example does not work if I open a browser on a remote computer.
The page loads fine but the sockio connection fails.

**Comment by capaj** [comment]
Are you talking about https://github.com/capaj/Moonridge/tree/master/test/e2e-smoketest ? Have you changed the url in https://github.com/capaj/Moonridge/blob/master/test/e2e-smoketest/showcase.js#L97 the example to point to the remote computer?

**Comment by ruimgoncalves** [comment]
Yeap, changing the url did the trick, thanks.
